ros2_node:
  cal_timer_period: 0.01
  pub_timer_period: 0.01

mppi:
  package_name: "mppi_solver"
  urdf_name: "floating_canadarm.urdf"
  controller_name: "/floating_canadarm_joint_controller"
  horizon: 32
  sample: 1000
  action: 13
  dt: 0.01
  free_floating: True
  base_move: True
  alpha: 0.1
  gamma: 0.98
  _lambda: 0.1
  manipulator_dof: 7
  mobile_dof: 6
  joint_order: ["v_x_joint", "v_y_joint", "v_z_joint", "v_r_joint", "v_p_joint", "v_yaw_joint", 
                "Base_Joint", "Shoulder_Roll", "Shoulder_Yaw", "Elbow_Pitch", "Wrist_Pitch", "Wrist_Yaw", "Wrist_Roll"]

cost:
  pose:
    stage_pose_weight: 40.0
    stage_orientation_weight: 125.0
    terminal_pose_weight: 75.0
    terminal_orientation_weight: 250.0

  covariance: 
    weight: 0.005

  action:
    weight: 0.0005
  
  joint_space:
    centering_weight: 1.0
    tracking_weight: 0.05

  collision:
    weight: 100000.0
    softcap: 0.5

sample:
  sigma_scale: 3.0
  kappa: 0.005
  sigma_update: true
  sigma_update_type: "CMA_ES"
  standard:
    step_size_cov: 0.2

wrapper:
  package_name: 'mppi_controller'
  urdf_name: 'floating_canadarm.urdf'
