ros2_node:
  cal_timer_period: 0.01
  pub_timer_period: 0.01

mppi:
  package_name: "mppi_solver"
  urdf_name: "floating_canadarm.urdf"
  controller_name: "/floating_canadarm_joint_controller"
  horizon: 32
  sample: 4096
  action: 13
  dt: 0.01
  free_floating: True
  base_move: True
  alpha: 0.1
  gamma: 0.98
  _lambda: 0.045
  manipulator_dof: 7
  mobile_dof: 6
  joint_order: ["v_x_joint", "v_y_joint", "v_z_joint", "v_r_joint", "v_p_joint", "v_yaw_joint", 
                "Base_Joint", "Shoulder_Roll", "Shoulder_Yaw", "Elbow_Pitch", "Wrist_Pitch", "Wrist_Yaw", "Wrist_Roll"]
  compile: False
  
cost:
  pose:
    stage_pose_weight: 40.0
    stage_orientation_weight: 175.0
    terminal_pose_weight: 75.0
    terminal_orientation_weight: 350.0

  covariance: 
    weight: 0.005

  action:
    weight: 0.00035
  
  joint_space:
    centering_weight: 1.0
    tracking_weight: 3.0
  
  collision:
    weight: 10000.0
    softcap: 0.4

  stop:
    weight: 0.2
    v_max: [ 0.0698132, 0.0698132, 0.0698132, 0.0698132, 0.0698132, 0.0698132, 0.0698132 ]

  end_effector:
    weight: 0.25
    distance_limit: 2.0

  reference:
    weight: 0.45

  base_disturbance:
    weight: 0.75

sample:
  selection: ['std', 'sobol', 'std_scaling', 'std_constacc_scaling', 'std_constacc', 'sobol_constacc']
  selection_weights: [ 0.0, 0.0, 0.0, 0.5, 0.5, 0.0 ]
  sigma_scale: 3.0
  kappa: 0.005
  sigma_update: true
  sigma_update_type: "CMA_ES"
  seed: 0
  bspline:
    knot: 8
  standard:
    step_size_cov: 0.2

wrapper:
  package_name: 'mppi_controller'
  urdf_name: 'floating_canadarm.urdf'
