ros2_node:
  cal_timer_period: 0.01
  pub_timer_period: 0.01

mppi:
  package_name: "mppi_solver"
  urdf_name: "SSRMS_Canadarm2_w_iss.urdf"
  controller_name: "/canadarm_joint_controller"
  horizon: 32
  sample: 4096
  action: 7
  dt: 0.01
  free_floating: False
  base_move: False
  alpha: 0.1
  gamma: 0.98
  _lambda: 0.06
  manipulator_dof: 7
  mobile_dof: 0
  joint_order: ["Base_Joint", "Shoulder_Roll", "Shoulder_Yaw", "Elbow_Pitch", "Wrist_Pitch", "Wrist_Yaw", "Wrist_Roll"]

cost:
  pose:
    stage_pose_weight: 40.0
    stage_orientation_weight: 150.0
    terminal_pose_weight: 75.0
    terminal_orientation_weight: 300.0

  covariance: 
    weight: 0.005

  action:
    weight: 0.00025
  
  joint_space:
    centering_weight: 1.0
    tracking_weight: 3.0
  
  collision:
    weight: 10000.0
    softcap: 0.4

  stop:
    weight: 0.1
    v_max: [ 0.0698132, 0.0698132, 0.0698132, 0.0698132, 0.0698132, 0.0698132, 0.0698132 ]

  end_effector:
    weight: 0.175
    distance_limit: 1.5

  reference:
    weight: 0.75

  base_disturbance:
    weight: 1.0

sample:
  sigma_scale: 3.0
  kappa: 0.005
  sigma_update: true
  sigma_update_type: "CMA_ES"
  seed: 0
  bspline:
    knot: 8
  standard:
    step_size_cov: 0.2

wrapper:
  package_name: 'mppi_controller'
  urdf_name: 'Canadarm2_w_iss.urdf'
